import type { Metadata } from 'next';
import { Cuprum } from 'next/font/google';
import './globals.css';

const inter = Cuprum({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.className} bg-gray-400 h-screen flex items-center justify-center`}>
				<section className='max-w-screen-lg mx-auto '>{children}</section>
			</body>
		</html>
	);
}
